import { WebsiteState, COLOR_THEMES } from "./constants";

// Function to generate CSS
export const generateCSS = (data: WebsiteState): string => {
  const { colorTheme, customCSS } = data;
  const theme = COLOR_THEMES[colorTheme] || COLOR_THEMES.modern;
  
  return `/* 
  Website Styles 
  Generated by Business Website Builder
*/

/* Variables */
:root {
  --primary: ${theme.primary};
  --secondary: ${theme.secondary};
  --accent: ${theme.accent};
  --text: ${theme.text};
  --background: ${theme.background};
  --light-bg: ${theme.lightBg};
  --transition: all 0.3s ease;
  --shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
  --border-radius: 4px;
  --container-width: 1200px;
}

/* Reset and Base Styles */
* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}

html {
  scroll-behavior: smooth;
}

body {
  font-family: 'Arial', sans-serif;
  color: var(--text);
  background-color: var(--background);
  line-height: 1.6;
}

a {
  color: var(--primary);
  text-decoration: none;
  transition: var(--transition);
}

a:hover {
  color: var(--secondary);
}

img {
  max-width: 100%;
  height: auto;
}

.container {
  width: 100%;
  max-width: var(--container-width);
  margin: 0 auto;
  padding: 0 20px;
}

/* Buttons */
.btn-primary {
  display: inline-block;
  background-color: var(--primary);
  color: white;
  padding: 10px 20px;
  border-radius: var(--border-radius);
  font-weight: 600;
  text-align: center;
  transition: var(--transition);
  border: none;
  cursor: pointer;
}

.btn-primary:hover {
  background-color: var(--secondary);
  color: white;
  transform: translateY(-2px);
  box-shadow: var(--shadow);
}

.btn-secondary {
  display: inline-block;
  background-color: transparent;
  color: var(--primary);
  padding: 10px 20px;
  border-radius: var(--border-radius);
  font-weight: 600;
  text-align: center;
  transition: var(--transition);
  border: 1px solid var(--primary);
  cursor: pointer;
}

.btn-secondary:hover {
  background-color: var(--primary);
  color: white;
}

/* Navigation */
.navbar {
  background-color: var(--background);
  box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
  position: sticky;
  top: 0;
  z-index: 100;
  padding: 15px 0;
}

.navbar .container {
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.logo {
  font-size: 1.5rem;
  font-weight: 700;
  color: var(--primary);
}

.logo img {
  max-height: 40px;
}

.nav-links {
  display: flex;
  align-items: center;
  gap: 20px;
}

.nav-links a {
  color: var(--text);
  font-weight: 500;
}

.nav-links a:hover {
  color: var(--primary);
}

.mobile-menu-btn {
  display: none;
  flex-direction: column;
  gap: 5px;
  cursor: pointer;
}

.mobile-menu-btn span {
  display: block;
  width: 25px;
  height: 3px;
  background-color: var(--text);
  border-radius: 5px;
  transition: var(--transition);
}

/* Hero Section */
.hero {
  padding: 100px 0;
  background-color: var(--light-bg);
  text-align: center;
}

.hero h1 {
  font-size: 2.5rem;
  color: var(--text);
  margin-bottom: 20px;
  font-weight: 700;
}

.hero p {
  font-size: 1.2rem;
  color: var(--text);
  max-width: 700px;
  margin: 0 auto 30px;
}

/* Features Section */
.features {
  padding: 80px 0;
  background-color: var(--background);
}

.features h2,
.portfolio h2,
.testimonials h2,
.partners h2,
.contact h2 {
  text-align: center;
  font-size: 2rem;
  margin-bottom: 50px;
  color: var(--text);
}

.features-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
  gap: 30px;
}

.feature-card {
  background-color: var(--background);
  border-radius: var(--border-radius);
  padding: 30px;
  text-align: center;
  box-shadow: var(--shadow);
  transition: var(--transition);
}

.feature-card:hover {
  transform: translateY(-5px);
  box-shadow: 0 10px 20px rgba(0, 0, 0, 0.1);
}

.feature-icon {
  font-size: 2.5rem;
  color: var(--primary);
  margin-bottom: 20px;
}

.feature-card h3 {
  font-size: 1.2rem;
  margin-bottom: 15px;
  color: var(--text);
}

.feature-card p {
  color: var(--text);
  opacity: 0.9;
}

/* Portfolio Section */
.portfolio {
  padding: 80px 0;
  background-color: var(--light-bg);
}

.portfolio-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
  gap: 20px;
}

.portfolio-item {
  position: relative;
  border-radius: var(--border-radius);
  overflow: hidden;
  box-shadow: var(--shadow);
  height: 250px;
}

.portfolio-image {
  width: 100%;
  height: 100%;
}

.portfolio-image img {
  width: 100%;
  height: 100%;
  object-fit: cover;
  transition: var(--transition);
}

.portfolio-overlay {
  position: absolute;
  bottom: 0;
  left: 0;
  right: 0;
  background-color: rgba(0, 0, 0, 0.7);
  color: white;
  padding: 20px;
  transform: translateY(100%);
  transition: var(--transition);
}

.portfolio-item:hover .portfolio-overlay {
  transform: translateY(0);
}

.portfolio-item:hover .portfolio-image img {
  transform: scale(1.1);
}

.portfolio-overlay h3 {
  font-size: 1.2rem;
  margin-bottom: 10px;
}

.portfolio-overlay p {
  font-size: 0.9rem;
  opacity: 0.9;
}

/* Testimonials Section */
.testimonials {
  padding: 80px 0;
  background-color: var(--background);
}

.testimonials-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
  gap: 30px;
}

.testimonial-card {
  background-color: var(--light-bg);
  border-radius: var(--border-radius);
  padding: 30px;
  box-shadow: var(--shadow);
  text-align: center;
}

.testimonial-image {
  width: 80px;
  height: 80px;
  border-radius: 50%;
  overflow: hidden;
  margin: 0 auto 20px;
  border: 3px solid var(--primary);
}

.testimonial-image img {
  width: 100%;
  height: 100%;
  object-fit: cover;
}

.placeholder-image {
  width: 100%;
  height: 100%;
  background-color: #ddd;
  display: flex;
  align-items: center;
  justify-content: center;
  color: #888;
}

.testimonial-text {
  font-style: italic;
  margin-bottom: 20px;
  color: var(--text);
}

.testimonial-author {
  font-weight: 600;
  color: var(--text);
}

/* Partners Section */
.partners {
  padding: 60px 0;
  background-color: var(--light-bg);
}

.partners-grid {
  display: flex;
  flex-wrap: wrap;
  justify-content: center;
  align-items: center;
  gap: 40px;
}

.partner-logo {
  max-width: 180px;
  filter: grayscale(100%);
  opacity: 0.7;
  transition: var(--transition);
}

.partner-logo:hover {
  filter: grayscale(0);
  opacity: 1;
}

.partner-logo img {
  width: 100%;
  height: auto;
}

/* Contact Section */
.contact {
  padding: 80px 0;
  background-color: var(--light-bg);
}

.contact-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
  gap: 40px;
}

.contact-info {
  display: flex;
  flex-direction: column;
  gap: 20px;
}

.contact-item {
  display: flex;
  align-items: center;
  gap: 15px;
}

.contact-item i {
  font-size: 1.2rem;
  color: var(--primary);
}

.contact-social {
  margin-top: 20px;
}

.contact-social h3 {
  font-size: 1.2rem;
  margin-bottom: 15px;
  color: var(--text);
}

.social-links {
  display: flex;
  gap: 15px;
}

.social-links a {
  display: flex;
  align-items: center;
  justify-content: center;
  width: 40px;
  height: 40px;
  background-color: var(--primary);
  color: white;
  border-radius: 50%;
  transition: var(--transition);
}

.social-links a:hover {
  background-color: var(--secondary);
  transform: translateY(-3px);
}

.contact-form {
  background-color: var(--background);
  padding: 30px;
  border-radius: var(--border-radius);
  box-shadow: var(--shadow);
}

.form-group {
  margin-bottom: 20px;
}

.form-group label {
  display: block;
  margin-bottom: 5px;
  font-weight: 500;
  color: var(--text);
}

.form-group input,
.form-group textarea {
  width: 100%;
  padding: 10px;
  border: 1px solid #ddd;
  border-radius: var(--border-radius);
  font-size: 1rem;
  transition: var(--transition);
}

.form-group input:focus,
.form-group textarea:focus {
  outline: none;
  border-color: var(--primary);
  box-shadow: 0 0 0 2px rgba(var(--primary-rgb), 0.1);
}

.newsletter-form-container {
  background-color: var(--background);
  padding: 30px;
  border-radius: var(--border-radius);
  box-shadow: var(--shadow);
}

.newsletter-form-container h3 {
  font-size: 1.2rem;
  margin-bottom: 10px;
  color: var(--text);
}

.newsletter-form-container p {
  margin-bottom: 20px;
  color: var(--text);
  opacity: 0.9;
}

.newsletter-form {
  display: flex;
  gap: 10px;
}

.newsletter-form input {
  flex: 1;
  padding: 10px;
  border: 1px solid #ddd;
  border-radius: var(--border-radius);
  font-size: 1rem;
}

.newsletter-form input:focus {
  outline: none;
  border-color: var(--primary);
}

/* Footer */
footer {
  background-color: var(--text);
  color: white;
  padding: 60px 0 20px;
}

.footer-content {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
  gap: 40px;
  margin-bottom: 40px;
}

.footer-section h3 {
  font-size: 1.2rem;
  margin-bottom: 20px;
  color: white;
}

.footer-section p {
  opacity: 0.8;
  margin-bottom: 15px;
}

.footer-section a {
  color: white;
  opacity: 0.8;
}

.footer-section a:hover {
  opacity: 1;
  color: var(--accent);
}

.footer-links {
  list-style: none;
}

.footer-links li {
  margin-bottom: 10px;
}

.footer-bottom {
  text-align: center;
  padding-top: 20px;
  border-top: 1px solid rgba(255, 255, 255, 0.1);
}

.footer-bottom p {
  opacity: 0.7;
  font-size: 0.9rem;
}

/* Responsive Styles */
@media (max-width: 768px) {
  .mobile-menu-btn {
    display: flex;
  }

  .nav-links {
    position: absolute;
    top: 100%;
    left: 0;
    right: 0;
    background-color: var(--background);
    flex-direction: column;
    align-items: center;
    padding: 20px;
    box-shadow: 0 5px 10px rgba(0, 0, 0, 0.1);
    display: none;
  }

  .nav-links.active {
    display: flex;
  }

  .hero h1 {
    font-size: 2rem;
  }

  .hero p {
    font-size: 1rem;
  }

  .contact-grid,
  .features-grid,
  .testimonials-grid {
    grid-template-columns: 1fr;
  }

  .newsletter-form {
    flex-direction: column;
  }
}

/* Custom CSS */
${customCSS || ''}
`;
};

// Function to generate JavaScript
export const generateJavaScript = (): string => {
  return `// Mobile navigation toggle
document.addEventListener('DOMContentLoaded', function() {
  const mobileMenuBtn = document.querySelector('.mobile-menu-btn');
  const navLinks = document.querySelector('.nav-links');
  
  if (mobileMenuBtn && navLinks) {
    mobileMenuBtn.addEventListener('click', function() {
      navLinks.classList.toggle('active');
      mobileMenuBtn.classList.toggle('active');
    });
    
    // Close mobile menu when clicking outside
    document.addEventListener('click', function(e) {
      if (!mobileMenuBtn.contains(e.target) && !navLinks.contains(e.target)) {
        navLinks.classList.remove('active');
        mobileMenuBtn.classList.remove('active');
      }
    });
  }
  
  // Smooth scrolling for anchor links
  document.querySelectorAll('a[href^="#"]').forEach(anchor => {
    anchor.addEventListener('click', function (e) {
      e.preventDefault();
      
      const targetId = this.getAttribute('href');
      if (targetId === '#') return;
      
      const targetElement = document.querySelector(targetId);
      if (targetElement) {
        targetElement.scrollIntoView({
          behavior: 'smooth'
        });
        
        // Close mobile menu after clicking
        if (navLinks && mobileMenuBtn) {
          navLinks.classList.remove('active');
          mobileMenuBtn.classList.remove('active');
        }
      }
    });
  });
  
  // Handle contact form submission
  const contactForm = document.getElementById('contact-form');
  if (contactForm) {
    contactForm.addEventListener('submit', function(e) {
      e.preventDefault();
      
      // In a real implementation, you would send the form data to a server
      const formData = new FormData(contactForm);
      const formValues = {};
      
      formData.forEach((value, key) => {
        formValues[key] = value;
      });
      
      // For demo purposes, we'll just show an alert
      alert('Thank you for your message! We will get back to you soon.');
      contactForm.reset();
    });
  }
  
  // Handle newsletter form submission
  const newsletterForm = document.getElementById('newsletter-form');
  if (newsletterForm) {
    newsletterForm.addEventListener('submit', function(e) {
      e.preventDefault();
      
      // For demo purposes, we'll just show an alert
      alert('Thank you for subscribing to our newsletter!');
      newsletterForm.reset();
    });
  }
});
`;
};
